### ISSUE TITLE
question / suggestion: are all the code capable with / optimized for x86_64 instructions?

### ISSUE THREAD

**Issue by fyears** [tuhdo/os01#40]
Hi,

I am reading your book, and the book seems to be capable with 32 bit processor rather than 64 bit processor. For example, in Chapter 4 "x86 Assembly and C" you introduce x84 assembly, and in Chapter 6 "Runtime inspection and debug" you intentionally compile C program with `-m32` flag.

My (limited) understanding is that assembly for x86 and x64 has some (significant) differences, and surely debugging x64 gcc program differs, too. And nowadays (year 2017) almost all new-released personal computers are using 64 bit processors.

Is it unnecessary to notice the differences? Or sufficient to write codes for 32 bit processors in almost all computers (every practical codes are written in this way)?

I am definitely a newbie here, so maybe I am missing something.

Thank you.

**Comment by tuhdo** [comment]
Hi,

Yes, it is intentional that way because the book is planned for you to write a 32-bit OS. Even if today we have 64-bit processors, we still have many 32-bit applications, in particular on Windows. Besides, writing 32-bit code is easier for educational purpose. If you write 64-bit code, you will need to take care the extra requirements for 64-bit mode (you can see in Volume 3, each chapter always has a few extra sections for IA-32e mode, which enables a 64-bit operating environment), which makes writing the OS more complicated for beginners. Rather, I use 32-bit to shorten the time to complete a simple OS. Once a reader learned the hang of writing an OS, he can extend the code to handle 64-bit requirements on his own.

**Comment by fyears** [comment]
Hi,

OK, I understand that now. I was curious that all write-an-OS book were written for 32-bit OS...

Suggestion: consider copying this explanation to somewhere in your book? :-)
