### ISSUE TITLE
Examples 4.5.2 and 4.5.3

### ISSUE THREAD

**Issue by gbip** [tuhdo/os01#69]
It seems that the example 4.5.2 is generated with 16-bit code and the example 4.5.3 is generated with 32 bit code.

## Example 4.5.2
The book says 
>jmp [0x1234]
>Then, the machine code is:
>ff 26 34 12

And it works with the following instructions for nasm :
```
bits 16
jmp [0x1234]
```

## Example 4.5.3
The book says :
>add eax, ecx
>Then the machine code is:
>01 c8

But assembling this :
```
bits 16
add eax, ecx
```
Gives  `66 01 c8`, while assembling :
```
bits 16
add eax, ecx
```
gives the expected result.

By the way, thanks for this book, it is really usefull, I am learning assembly with it in the hope to be able to complete Exercise 7.5.1 (I saw that there is some code in the repos, but I don't want to look at it at the moment).

**Comment by tuhdo** [comment]
Thanks. I will look into it. 

And I'm glad you are enjoying the book.

**Comment by tuhdo** [comment]
It is not wrong. `66h` is opcode override prefix, which is used to switch between 16- and 32-bit operand sizes. The prefix is used to select non-default size, which is 16-bit if the OS is currently operating in 32-bit protected mode, and is 32-bit otherwise. Quoted from section 2.1.1, "Instruction prefixes", vol 1:

> The operand-size override prefix allows a program to switch between 16- and 32-bit operand sizes. Either size can be the default; use of the prefix selects the non-default size.

I will need to mention this in the text.

**Comment by tuhdo** [comment]
Ok I updated the book. Thanks.
